platform :ios,'9.0'
target 'NAVi_base'do
    pod 'AFNetworking', '~> 2.6.0'
    pod 'AFNetworking/Serialization', '~> 2.6.0'
    pod 'AFNetworking/Security', '~> 2.6.0'
    pod 'AFNetworking/Reachability', '~> 2.6.0'
    pod 'AFNetworking/NSURLConnection', '~> 2.6.0'
    pod 'AFNetworking/NSURLSession', '~> 2.6.0'
    pod 'AFNetworking/UIKit', '~> 2.6.0'
    pod 'SDWebImage', '~>4.0'
    pod 'MBProgressHUD'
    pod 'TAPageControl'
    pod 'GoogleTagManager', '~> 3.12.1'
    pod 'Masonry'
    pod 'ReactiveCocoa','~>2.5.0'
end
target 'NAVi_akita'do
    pod 'AFNetworking', '~> 2.6.0'
    pod 'AFNetworking/Serialization', '~> 2.6.0'
    pod 'AFNetworking/Security', '~> 2.6.0'
    pod 'AFNetworking/Reachability', '~> 2.6.0'
    pod 'AFNetworking/NSURLConnection', '~> 2.6.0'
    pod 'AFNetworking/NSURLSession', '~> 2.6.0'
    pod 'AFNetworking/UIKit', '~> 2.6.0'
    pod 'SDWebImage', '~>4.0'
    pod 'MBProgressHUD'
    pod 'TAPageControl'
    pod 'GoogleTagManager', '~> 3.12.1'
    pod 'Masonry'
    pod 'ReactiveCocoa','~>2.5.0'
end
target 'NAVi_gifu'do
    pod 'AFNetworking', '~> 2.6.0'
    pod 'AFNetworking/Serialization', '~> 2.6.0'
    pod 'AFNetworking/Security', '~> 2.6.0'
    pod 'AFNetworking/Reachability', '~> 2.6.0'
    pod 'AFNetworking/NSURLConnection', '~> 2.6.0'
    pod 'AFNetworking/NSURLSession', '~> 2.6.0'
    pod 'AFNetworking/UIKit', '~> 2.6.0'
    pod 'SDWebImage', '~>4.0'
    pod 'MBProgressHUD'
    pod 'TAPageControl'
    pod 'GoogleTagManager', '~> 3.12.1'
    pod 'Masonry'
    pod 'ReactiveCocoa','~>2.5.0'
end
target 'NAVi_yomi'do
    pod 'AFNetworking', '~> 2.6.0'
    pod 'AFNetworking/Serialization', '~> 2.6.0'
    pod 'AFNetworking/Security', '~> 2.6.0'
    pod 'AFNetworking/Reachability', '~> 2.6.0'
    pod 'AFNetworking/NSURLConnection', '~> 2.6.0'
    pod 'AFNetworking/NSURLSession', '~> 2.6.0'
    pod 'AFNetworking/UIKit', '~> 2.6.0'
    pod 'SDWebImage', '~>4.0'
    pod 'MBProgressHUD'
    pod 'TAPageControl'
    pod 'GoogleTagManager', '~> 3.12.1'
    pod 'Masonry'
    pod 'ReactiveCocoa','~>2.5.0'
end
